import type { DeploymentTarget, DrizzleConnectionProfile, ExternalAuditReceipt, ExternalCapabilityPermit, ExternalPolicyBoundary, ExternalTraceBridge, InfrastructureConnector, InfrastructureIsolationBoundary, InfrastructureProvider, IntegrationTrustProfile, KyvernoPolicyCheck, MCPExternalConnector, MCPRuntimeBridge, MCPToolExecutionGateway, MCPUIRuntimeBinding, MilvusConnectionProfile, RealDeploymentSession, RealExecutionReceipt, RuntimeSandbox, SandboxExecutionSession, SecretVaultReference, TailscaleMeshSession, TerraformApplyRequest, TerraformPlanPreview, VaultSecretReference } from "./types.js";

export const registerInfrastructureProvider = (providers: InfrastructureProvider[], provider: InfrastructureProvider): InfrastructureProvider[] => [...providers, { ...provider, enabled: false }];
export const validateExternalBoundary = (boundary: ExternalPolicyBoundary): boolean => boundary.policyDecisionRequired && boundary.constitutionalDecisionRequired && boundary.tenantProjectScopeRequired;
export const createSandboxExecution = (sandbox: RuntimeSandbox): SandboxExecutionSession => ({ id: "sandbox-session", sandboxId: "sandbox-1", dryRun: true, started: true, completed: false });
export const executeSandboxedOperation = (session: SandboxExecutionSession): SandboxExecutionSession => ({ ...session, completed: true });
export const verifyInfrastructureIsolation = (boundary: InfrastructureIsolationBoundary): boolean => boundary.tenantIsolated && boundary.networkIsolated && boundary.secretIsolated && boundary.traceIsolated;
export const createDeploymentSession = (target: DeploymentTarget, approvalApproved: boolean): RealDeploymentSession => ({ id: `deploy-${target.environment}`, target, approvalApproved });
export const validateDeploymentTarget = (target: DeploymentTarget): boolean => target.previewReady && (target.environment === "local" || (target.kyvernoReady && target.tailscaleReady));
export const bridgeExternalTrace = (providerId: string, traceId: string): ExternalTraceBridge => ({ providerId, traceId, bridged: true });
export const verifyExternalAuditability = (receipt: ExternalAuditReceipt): boolean => receipt.replayMetadata.length > 0;
export const rollbackExternalMutation = (operationId: string): { operationId: string; rolledBack: boolean } => ({ operationId, rolledBack: true });
export const revokeExternalCapability = (capabilityId: string): ExternalCapabilityPermit => ({ capabilityId, granted: false, reason: "revoked" });
export const calculateIntegrationTrust = (profile: IntegrationTrustProfile): IntegrationTrustProfile => ({ ...profile, score: Math.max(0, Math.min(1, profile.score)) });
export const freezeExternalExecution = (operationId: string): RealExecutionReceipt => ({ id: `freeze-${operationId}`, operationId, status: "blocked", replayable: true });
export const replayExternalExecution = (receipt: RealExecutionReceipt): string[] => [receipt.operationId, receipt.status, "replayed"];
export const resolveVaultSecretReference = (ref: SecretVaultReference): VaultSecretReference | null => ref.provider === "hashicorp-vault" ? { provider: "hashicorp-vault", path: ref.path, key: ref.key } : null;
export const redactExternalSecretOutput = (output: string): string => output.replace(/(token|password|secret)\s*[:=]\s*[^\s,;]+/gi, "$1=[REDACTED]");
export const createTerraformPlanPreview = (target: string, diffSummary: string): TerraformPlanPreview => ({ id: `tf-plan-${target}`, target, diffSummary, sandboxed: true });
export const validateTerraformApplyRequest = (r: TerraformApplyRequest): boolean => !r.forceDestroy && r.approvalPackageApproved && r.policyDecisionAllow && r.constitutionalValidationPassed && r.rollbackPlanExists && r.blastRadiusWithinThreshold && (r.environment !== "production" || r.promotionExplicit) && r.traceReceiptEmitted && r.ledgerEntryRecorded;
export const verifyKyvernoPolicyReadiness = (check: KyvernoPolicyCheck): boolean => check.ready;
export const verifyTailscalePrivateMesh = (mesh: TailscaleMeshSession): boolean => mesh.privateAdminAccess && mesh.workerToControlPlane && mesh.emergencyOperatorAccess && mesh.observabilityAccess && mesh.zeroTrustRouting;
export const verifyDrizzleDatabaseBoundary = (profile: DrizzleConnectionProfile): boolean => profile.provider === "drizzle" && profile.prismaBlocked && profile.tenantBoundaryValidated && profile.appendOnlyLedgerCompatible;
export const verifyMilvusVectorBoundary = (profile: MilvusConnectionProfile): boolean => profile.provider === "milvus" && profile.tenantId.length > 0 && profile.projectId.length > 0;
export const createMCPRuntimeBridge = (): MCPRuntimeBridge => ({ id: "mcp-runtime-bridge", policyBound: true, constitutionalBound: true });
export const registerMCPExternalConnector = (connectors: MCPExternalConnector[], connector: MCPExternalConnector): MCPExternalConnector[] => [...connectors, { ...connector, enabled: false }];
export const createMCPToolExecutionGateway = (): MCPToolExecutionGateway => ({ id: "mcp-tool-gateway", policyRequired: true, constitutionalRequired: true, secretByReferenceOnly: true });
export const bindMCPUIRuntimeAction = (actionId: string, gatewayId: string): MCPUIRuntimeBinding => ({ actionId, gatewayId, governanceBound: true });
export const validateMCPExternalExecution = (connector: MCPExternalConnector, gateway: MCPToolExecutionGateway, policyPassed: boolean, constitutionalPassed: boolean, auditReceipt: boolean, replayMetadata: boolean, secretByValue: boolean): boolean => !connector.enabled && connector.requiresAuditReceipt && connector.replayable && gateway.policyRequired && gateway.constitutionalRequired && gateway.secretByReferenceOnly && policyPassed && constitutionalPassed && auditReceipt && replayMetadata && !secretByValue;
export const validateConnectorDisabledByDefault = (connector: InfrastructureConnector): boolean => !connector.enabled;
