export type WorkflowState =
  | "DRAFT"
  | "SPEC_READY"
  | "APPROVAL_REQUIRED"
  | "APPROVED"
  | "IMPLEMENTATION_ALLOWED"
  | "IMPLEMENTED"
  | "VERIFIED"
  | "COMPLETED"
  | "REVISION_REQUESTED"
  | "BACKLOG_CREATED"
  | "REJECTED"
  | "CLARIFICATION_REQUIRED"
  | "ESCALATED"
  | "BLOCKED";

const transitions: Record<WorkflowState, WorkflowState[]> = {
  DRAFT: ["SPEC_READY", "CLARIFICATION_REQUIRED", "REJECTED"],
  SPEC_READY: ["APPROVAL_REQUIRED", "REVISION_REQUESTED"],
  APPROVAL_REQUIRED: ["APPROVED", "REJECTED", "ESCALATED"],
  APPROVED: ["IMPLEMENTATION_ALLOWED"],
  IMPLEMENTATION_ALLOWED: ["IMPLEMENTED", "BLOCKED"],
  IMPLEMENTED: ["VERIFIED", "REVISION_REQUESTED"],
  VERIFIED: ["COMPLETED", "REVISION_REQUESTED"],
  COMPLETED: [],
  REVISION_REQUESTED: ["SPEC_READY", "BACKLOG_CREATED"],
  BACKLOG_CREATED: ["DRAFT"],
  REJECTED: [],
  CLARIFICATION_REQUIRED: ["DRAFT", "SPEC_READY"],
  ESCALATED: ["APPROVAL_REQUIRED", "BLOCKED"],
  BLOCKED: ["ESCALATED", "REVISION_REQUESTED"]
};

export const canTransition = (from: WorkflowState, to: WorkflowState): boolean => transitions[from].includes(to);
